version: '3.8'

services:
  mysql:
    image: mysql:8.4.5
    container_name: mud-mk2-mysql
    restart: always
    environment:
      MYSQL_DATABASE: mudmk2db
      MYSQL_USER: muduser
      MYSQL_PASSWORD: mudpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

volumes:
  mysql-data: